version: "3"

services:
  webserver:
    build:
      context: ./bin/php74
    container_name: 'yii2-php74'
    restart: 'always'
    ports:
      - "81:80"
      - "444:443"
    links:
      - database
    volumes:
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
  database:
    build:
      context: "./bin/mariadb"
    container_name: 'yii2-database'
    restart: 'always'
    ports:
      - "3307:3306"
    volumes:
      - ./data/mariadb:/var/lib/mariadb
      - ./logs/mariadb:/var/log/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker