version: "3"

services:
  webserver:
    build: ./docker/php
    container_name: webserver
    volumes:
      - ./www:/var/www/html
    depends_on:
      - database
  nginx:
    image: nginx:1.17
    container_name: nginx
    ports:
      - 81:80
    volumes:
      - ./www:/var/www/html
      - ./docker/nginx/yii2.conf:/etc/nginx/conf.d/yii2.conf
    depends_on:
      - webserver
  database:
    build:
      context: ./bin/mariadb
    container_name: yii2-database
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./data/mariadb:/var/lib/mariadb
      - ./logs/mariadb:/var/log/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker